# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrodepartamento.ui'
#
# Created: Fri Jan  7 15:50:36 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_departamento(object):
    def setupUi(self, departamento):
        departamento.setObjectName("departamento")
        departamento.setEnabled(True)
        departamento.resize(539, 387)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/departamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        departamento.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(departamento)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtGui.QFrame(departamento)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btSalvar = QtGui.QPushButton(self.frame_4)
        self.btSalvar.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSalvar.setIcon(icon1)
        self.btSalvar.setFlat(True)
        self.btSalvar.setObjectName("btSalvar")
        self.horizontalLayout_4.addWidget(self.btSalvar)
        self.btCancelar = QtGui.QPushButton(self.frame_4)
        self.btCancelar.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCancelar.setIcon(icon2)
        self.btCancelar.setFlat(True)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_4.addWidget(self.btCancelar)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame = QtGui.QFrame(departamento)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.EditNome = QtGui.QLineEdit(self.frame)
        self.EditNome.setEnabled(True)
        self.EditNome.setObjectName("EditNome")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditNome)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.EditCentroCusto = QtGui.QLineEdit(self.frame)
        self.EditCentroCusto.setEnabled(True)
        self.EditCentroCusto.setObjectName("EditCentroCusto")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditCentroCusto)
        self.EditID = QtGui.QLineEdit(self.frame)
        self.EditID.setEnabled(False)
        self.EditID.setObjectName("EditID")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.EditID)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(departamento)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(departamento)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabela = QtGui.QTableView(self.frame_3)
        self.tabela.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela.setTabKeyNavigation(False)
        self.tabela.setAlternatingRowColors(True)
        self.tabela.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabela.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabela.setSortingEnabled(True)
        self.tabela.setObjectName("tabela")
        self.tabela.horizontalHeader().setSortIndicatorShown(True)
        self.tabela.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tabela)
        self.verticalLayout_2.addWidget(self.frame_3)

        self.retranslateUi(departamento)
        QtCore.QMetaObject.connectSlotsByName(departamento)

    def retranslateUi(self, departamento):
        departamento.setWindowTitle(QtGui.QApplication.translate("departamento", "Cadastro de departamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.btSalvar.setText(QtGui.QApplication.translate("departamento", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.btCancelar.setText(QtGui.QApplication.translate("departamento", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("departamento", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("departamento", "Centro de custo", None, QtGui.QApplication.UnicodeUTF8))
        self.EditCentroCusto.setInputMask(QtGui.QApplication.translate("departamento", "#.##.## ; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("departamento", "Departamentos Cadastrados", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
