# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Fri Jan  7 22:23:34 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_principal(object):
    def setupUi(self, principal):
        principal.setObjectName("principal")
        principal.resize(450, 359)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(principal.sizePolicy().hasHeightForWidth())
        principal.setSizePolicy(sizePolicy)
        principal.setMinimumSize(QtCore.QSize(100, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        principal.setWindowIcon(icon)
        principal.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(principal)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 489))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 57, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/images/key.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/images/login.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("None")
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.EditUser = QtGui.QLineEdit(self.frame_2)
        self.EditUser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.EditUser.setObjectName("EditUser")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.EditUser)
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.EditSenha = QtGui.QLineEdit(self.frame_2)
        self.EditSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.EditSenha.setEchoMode(QtGui.QLineEdit.Password)
        self.EditSenha.setObjectName("EditSenha")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditSenha)
        self.btEntrar = QtGui.QPushButton(self.frame_2)
        self.btEntrar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btEntrar.setStyleSheet("None")
        self.btEntrar.setObjectName("btEntrar")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.btEntrar)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/images/gnome-session-logout.png"))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(151, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 56, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(152, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(principal)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 25))
        self.menubar.setStyleSheet("None")
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtGui.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuPedidos = QtGui.QMenu(self.menubar)
        self.menuPedidos.setObjectName("menuPedidos")
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        principal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(principal)
        self.statusbar.setObjectName("statusbar")
        principal.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(principal)
        self.toolBar.setEnabled(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        principal.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionCadastrar_Usuarios = QtGui.QAction(principal)
        self.actionCadastrar_Usuarios.setCheckable(False)
        self.actionCadastrar_Usuarios.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/User-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Usuarios.setIcon(icon1)
        self.actionCadastrar_Usuarios.setVisible(True)
        self.actionCadastrar_Usuarios.setIconVisibleInMenu(True)
        self.actionCadastrar_Usuarios.setObjectName("actionCadastrar_Usuarios")
        self.actionCadastrar_Tecnicos = QtGui.QAction(principal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/technical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Tecnicos.setIcon(icon2)
        self.actionCadastrar_Tecnicos.setIconVisibleInMenu(True)
        self.actionCadastrar_Tecnicos.setObjectName("actionCadastrar_Tecnicos")
        self.actionCadastrar_Equipamentos = QtGui.QAction(principal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/HP-Mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Equipamentos.setIcon(icon3)
        self.actionCadastrar_Equipamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_Equipamentos.setObjectName("actionCadastrar_Equipamentos")
        self.actionCadastrar_Departamentos = QtGui.QAction(principal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/departamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Departamentos.setIcon(icon4)
        self.actionCadastrar_Departamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_Departamentos.setObjectName("actionCadastrar_Departamentos")
        self.actionCadastrar_SubDepartamentos = QtGui.QAction(principal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/subdepartamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_SubDepartamentos.setIcon(icon5)
        self.actionCadastrar_SubDepartamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_SubDepartamentos.setObjectName("actionCadastrar_SubDepartamentos")
        self.actionRealizar_Pedido_de_Compra = QtGui.QAction(principal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/pedidodecompra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizar_Pedido_de_Compra.setIcon(icon6)
        self.actionRealizar_Pedido_de_Compra.setIconVisibleInMenu(True)
        self.actionRealizar_Pedido_de_Compra.setObjectName("actionRealizar_Pedido_de_Compra")
        self.actionRealizar_Baixa_no_Estoque = QtGui.QAction(principal)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/images/baixaestoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizar_Baixa_no_Estoque.setIcon(icon7)
        self.actionRealizar_Baixa_no_Estoque.setIconVisibleInMenu(True)
        self.actionRealizar_Baixa_no_Estoque.setObjectName("actionRealizar_Baixa_no_Estoque")
        self.actionDocumenta_o = QtGui.QAction(principal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/images/Book-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumenta_o.setIcon(icon8)
        self.actionDocumenta_o.setIconVisibleInMenu(True)
        self.actionDocumenta_o.setObjectName("actionDocumenta_o")
        self.actionSobre = QtGui.QAction(principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/images/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre.setIcon(icon9)
        self.actionSobre.setIconVisibleInMenu(True)
        self.actionSobre.setObjectName("actionSobre")
        self.actionAjuda_Programa = QtGui.QAction(principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjuda_Programa.setIcon(icon10)
        self.actionAjuda_Programa.setIconVisibleInMenu(True)
        self.actionAjuda_Programa.setObjectName("actionAjuda_Programa")
        self.actionSair = QtGui.QAction(principal)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/images/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSair.setIcon(icon11)
        self.actionSair.setObjectName("actionSair")
        self.actionSair2 = QtGui.QAction(principal)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_cancel2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSair2.setIcon(icon12)
        self.actionSair2.setObjectName("actionSair2")
        self.menuCadastros.addAction(self.actionCadastrar_Equipamentos)
        self.menuCadastros.addAction(self.actionCadastrar_Tecnicos)
        self.menuCadastros.addAction(self.actionCadastrar_Usuarios)
        self.menuCadastros.addAction(self.actionCadastrar_Departamentos)
        self.menuPedidos.addAction(self.actionRealizar_Pedido_de_Compra)
        self.menuPedidos.addAction(self.actionRealizar_Baixa_no_Estoque)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionDocumenta_o)
        self.menuAjuda.addAction(self.actionAjuda_Programa)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuPedidos.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionRealizar_Pedido_de_Compra)
        self.toolBar.addAction(self.actionRealizar_Baixa_no_Estoque)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCadastrar_Usuarios)
        self.toolBar.addAction(self.actionCadastrar_Tecnicos)
        self.toolBar.addAction(self.actionCadastrar_Equipamentos)
        self.toolBar.addAction(self.actionCadastrar_Departamentos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSair)

        self.retranslateUi(principal)
        QtCore.QMetaObject.connectSlotsByName(principal)

    def retranslateUi(self, principal):
        principal.setWindowTitle(QtGui.QApplication.translate("principal", "Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("principal", "Digite seus dados", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("principal", "Usuário", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("principal", "Senha", None, QtGui.QApplication.UnicodeUTF8))
        self.btEntrar.setText(QtGui.QApplication.translate("principal", "Entrar", None, QtGui.QApplication.UnicodeUTF8))
        self.btEntrar.setShortcut(QtGui.QApplication.translate("principal", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCadastros.setTitle(QtGui.QApplication.translate("principal", "Cadastros", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPedidos.setTitle(QtGui.QApplication.translate("principal", "Operações", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("principal", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("principal", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Usuarios.setText(QtGui.QApplication.translate("principal", "Cadastrar Usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Tecnicos.setText(QtGui.QApplication.translate("principal", "Cadastrar Tecnicos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Tecnicos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Tecnicos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Equipamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar Equipamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Equipamentos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Equipamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Departamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar Departamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Departamentos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Departamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_SubDepartamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar SubDepartamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Pedido_de_Compra.setText(QtGui.QApplication.translate("principal", "Realizar Pedido de Compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Baixa_no_Estoque.setText(QtGui.QApplication.translate("principal", "Realizar Baixa no Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Baixa_no_Estoque.setToolTip(QtGui.QApplication.translate("principal", "Realizar Baixa no Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumenta_o.setText(QtGui.QApplication.translate("principal", "Documentação", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setText(QtGui.QApplication.translate("principal", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAjuda_Programa.setText(QtGui.QApplication.translate("principal", "Ajuda Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAjuda_Programa.setToolTip(QtGui.QApplication.translate("principal", "Ajuda Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("principal", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair2.setText(QtGui.QApplication.translate("principal", "Sair2", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
