# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Sun Oct 10 00:24:34 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_principal(object):
    def setupUi(self, principal):
        principal.setObjectName("principal")
        principal.resize(575, 366)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(principal.sizePolicy().hasHeightForWidth())
        principal.setSizePolicy(sizePolicy)
        principal.setMinimumSize(QtCore.QSize(100, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        principal.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(principal)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 489))
        self.centralwidget.setObjectName("centralwidget")
        principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 23))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtGui.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuPedidos = QtGui.QMenu(self.menubar)
        self.menuPedidos.setObjectName("menuPedidos")
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        principal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(principal)
        self.statusbar.setObjectName("statusbar")
        principal.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(principal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        principal.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionCadastrar_Usuarios = QtGui.QAction(principal)
        self.actionCadastrar_Usuarios.setCheckable(False)
        self.actionCadastrar_Usuarios.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/User-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Usuarios.setIcon(icon1)
        self.actionCadastrar_Usuarios.setVisible(True)
        self.actionCadastrar_Usuarios.setIconVisibleInMenu(True)
        self.actionCadastrar_Usuarios.setObjectName("actionCadastrar_Usuarios")
        self.actionCadastrar_Tecnicos = QtGui.QAction(principal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/technical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Tecnicos.setIcon(icon2)
        self.actionCadastrar_Tecnicos.setIconVisibleInMenu(True)
        self.actionCadastrar_Tecnicos.setObjectName("actionCadastrar_Tecnicos")
        self.actionCadastrar_Equipamentos = QtGui.QAction(principal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/HP-Mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Equipamentos.setIcon(icon3)
        self.actionCadastrar_Equipamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_Equipamentos.setObjectName("actionCadastrar_Equipamentos")
        self.actionCadastrar_Departamentos = QtGui.QAction(principal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/departamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_Departamentos.setIcon(icon4)
        self.actionCadastrar_Departamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_Departamentos.setObjectName("actionCadastrar_Departamentos")
        self.actionCadastrar_SubDepartamentos = QtGui.QAction(principal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/subdepartamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar_SubDepartamentos.setIcon(icon5)
        self.actionCadastrar_SubDepartamentos.setIconVisibleInMenu(True)
        self.actionCadastrar_SubDepartamentos.setObjectName("actionCadastrar_SubDepartamentos")
        self.actionRealizar_Pedido_de_Compra = QtGui.QAction(principal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/pedidodecompra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizar_Pedido_de_Compra.setIcon(icon6)
        self.actionRealizar_Pedido_de_Compra.setIconVisibleInMenu(True)
        self.actionRealizar_Pedido_de_Compra.setObjectName("actionRealizar_Pedido_de_Compra")
        self.actionRealizar_Baixa_no_Estoque = QtGui.QAction(principal)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/images/baixaestoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizar_Baixa_no_Estoque.setIcon(icon7)
        self.actionRealizar_Baixa_no_Estoque.setIconVisibleInMenu(True)
        self.actionRealizar_Baixa_no_Estoque.setObjectName("actionRealizar_Baixa_no_Estoque")
        self.actionDocumenta_o = QtGui.QAction(principal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/images/Book-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumenta_o.setIcon(icon8)
        self.actionDocumenta_o.setIconVisibleInMenu(True)
        self.actionDocumenta_o.setObjectName("actionDocumenta_o")
        self.actionSobre = QtGui.QAction(principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/images/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre.setIcon(icon9)
        self.actionSobre.setIconVisibleInMenu(True)
        self.actionSobre.setObjectName("actionSobre")
        self.actionAjuda_Programa = QtGui.QAction(principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjuda_Programa.setIcon(icon10)
        self.actionAjuda_Programa.setIconVisibleInMenu(True)
        self.actionAjuda_Programa.setObjectName("actionAjuda_Programa")
        self.menuCadastros.addAction(self.actionCadastrar_Equipamentos)
        self.menuCadastros.addAction(self.actionCadastrar_Tecnicos)
        self.menuCadastros.addAction(self.actionCadastrar_Usuarios)
        self.menuCadastros.addAction(self.actionCadastrar_Departamentos)
        self.menuCadastros.addAction(self.actionCadastrar_SubDepartamentos)
        self.menuPedidos.addAction(self.actionRealizar_Pedido_de_Compra)
        self.menuPedidos.addAction(self.actionRealizar_Baixa_no_Estoque)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionDocumenta_o)
        self.menuAjuda.addAction(self.actionAjuda_Programa)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuPedidos.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionRealizar_Pedido_de_Compra)
        self.toolBar.addAction(self.actionRealizar_Baixa_no_Estoque)
        self.toolBar.addAction(self.actionCadastrar_Usuarios)
        self.toolBar.addAction(self.actionCadastrar_Tecnicos)
        self.toolBar.addAction(self.actionCadastrar_Equipamentos)
        self.toolBar.addAction(self.actionCadastrar_Departamentos)
        self.toolBar.addAction(self.actionCadastrar_SubDepartamentos)

        self.retranslateUi(principal)
        QtCore.QMetaObject.connectSlotsByName(principal)

    def retranslateUi(self, principal):
        principal.setWindowTitle(QtGui.QApplication.translate("principal", "Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCadastros.setTitle(QtGui.QApplication.translate("principal", "Cadastros", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPedidos.setTitle(QtGui.QApplication.translate("principal", "Operações", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("principal", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("principal", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Usuarios.setText(QtGui.QApplication.translate("principal", "Cadastrar Usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Tecnicos.setText(QtGui.QApplication.translate("principal", "Cadastrar Tecnicos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Tecnicos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Tecnicos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Equipamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar Equipamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Equipamentos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Equipamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Departamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar Departamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_Departamentos.setToolTip(QtGui.QApplication.translate("principal", "Cadastrar Departamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCadastrar_SubDepartamentos.setText(QtGui.QApplication.translate("principal", "Cadastrar SubDepartamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Pedido_de_Compra.setText(QtGui.QApplication.translate("principal", "Realizar Pedido de Compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Baixa_no_Estoque.setText(QtGui.QApplication.translate("principal", "Realizar Baixa no Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_Baixa_no_Estoque.setToolTip(QtGui.QApplication.translate("principal", "Realizar Baixa no Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumenta_o.setText(QtGui.QApplication.translate("principal", "Documentação", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setText(QtGui.QApplication.translate("principal", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAjuda_Programa.setText(QtGui.QApplication.translate("principal", "Ajuda Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAjuda_Programa.setToolTip(QtGui.QApplication.translate("principal", "Ajuda Easy Estoque", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
