# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroequipamentos.ui'
#
# Created: Thu Nov 25 00:16:02 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_equipamento(object):
    def setupUi(self, equipamento):
        equipamento.setObjectName("equipamento")
        equipamento.resize(668, 593)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/HP-Mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        equipamento.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(equipamento)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtGui.QFrame(equipamento)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btNovo = QtGui.QPushButton(self.frame_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btNovo.setIcon(icon1)
        self.btNovo.setFlat(True)
        self.btNovo.setObjectName("btNovo")
        self.horizontalLayout_2.addWidget(self.btNovo)
        self.btSalvar = QtGui.QPushButton(self.frame_3)
        self.btSalvar.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSalvar.setIcon(icon2)
        self.btSalvar.setFlat(True)
        self.btSalvar.setObjectName("btSalvar")
        self.horizontalLayout_2.addWidget(self.btSalvar)
        self.btCancelar = QtGui.QPushButton(self.frame_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCancelar.setIcon(icon3)
        self.btCancelar.setFlat(True)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_2.addWidget(self.btCancelar)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(equipamento)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.EditUnidade = QtGui.QLineEdit(self.frame_2)
        self.EditUnidade.setEnabled(False)
        self.EditUnidade.setObjectName("EditUnidade")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.EditUnidade)
        self.EditMarca = QtGui.QLineEdit(self.frame_2)
        self.EditMarca.setEnabled(False)
        self.EditMarca.setObjectName("EditMarca")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditMarca)
        self.EditNome = QtGui.QLineEdit(self.frame_2)
        self.EditNome.setEnabled(False)
        self.EditNome.setObjectName("EditNome")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditNome)
        self.EditID = QtGui.QLineEdit(self.frame_2)
        self.EditID.setEnabled(False)
        self.EditID.setObjectName("EditID")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.EditID)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.EditPatrimonio = QtGui.QLineEdit(self.frame_2)
        self.EditPatrimonio.setEnabled(False)
        self.EditPatrimonio.setEchoMode(QtGui.QLineEdit.Normal)
        self.EditPatrimonio.setObjectName("EditPatrimonio")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditPatrimonio)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.spinQtd = QtGui.QSpinBox(self.frame_2)
        self.spinQtd.setEnabled(False)
        self.spinQtd.setObjectName("spinQtd")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinQtd)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinEstMin = QtGui.QSpinBox(self.frame_2)
        self.spinEstMin.setEnabled(False)
        self.spinEstMin.setObjectName("spinEstMin")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinEstMin)
        self.comboReponsavel = QtGui.QComboBox(self.frame_2)
        self.comboReponsavel.setEnabled(False)
        self.comboReponsavel.setObjectName("comboReponsavel")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboReponsavel)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(equipamento)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.EditPesquisa = QtGui.QLineEdit(self.frame)
        self.EditPesquisa.setObjectName("EditPesquisa")
        self.horizontalLayout_4.addWidget(self.EditPesquisa)
        self.btBusca = QtGui.QPushButton(self.frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/find.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btBusca.setIcon(icon4)
        self.btBusca.setObjectName("btBusca")
        self.horizontalLayout_4.addWidget(self.btBusca)
        self.verticalLayout.addWidget(self.frame)
        self.frame_4 = QtGui.QFrame(equipamento)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabela = QtGui.QTableView(self.frame_4)
        self.tabela.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela.setTabKeyNavigation(False)
        self.tabela.setAlternatingRowColors(True)
        self.tabela.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabela.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabela.setSortingEnabled(True)
        self.tabela.setObjectName("tabela")
        self.tabela.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tabela)
        self.verticalLayout.addWidget(self.frame_4)
        self.label_3.setBuddy(self.EditUnidade)
        self.label_2.setBuddy(self.EditMarca)
        self.label.setBuddy(self.EditNome)
        self.label_5.setBuddy(self.EditPatrimonio)

        self.retranslateUi(equipamento)
        QtCore.QMetaObject.connectSlotsByName(equipamento)
        equipamento.setTabOrder(self.EditNome, self.EditMarca)
        equipamento.setTabOrder(self.EditMarca, self.EditUnidade)
        equipamento.setTabOrder(self.EditUnidade, self.EditPatrimonio)
        equipamento.setTabOrder(self.EditPatrimonio, self.btSalvar)
        equipamento.setTabOrder(self.btSalvar, self.btNovo)
        equipamento.setTabOrder(self.btNovo, self.EditID)
        equipamento.setTabOrder(self.EditID, self.btCancelar)
        equipamento.setTabOrder(self.btCancelar, self.tabela)

    def retranslateUi(self, equipamento):
        equipamento.setWindowTitle(QtGui.QApplication.translate("equipamento", "Cadastro de Equipamento", None, QtGui.QApplication.UnicodeUTF8))
        self.btNovo.setText(QtGui.QApplication.translate("equipamento", "Novo", None, QtGui.QApplication.UnicodeUTF8))
        self.btSalvar.setText(QtGui.QApplication.translate("equipamento", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.btCancelar.setText(QtGui.QApplication.translate("equipamento", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("equipamento", "Unidade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("equipamento", "Marca/Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("equipamento", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("equipamento", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("equipamento", "Patrimonio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("equipamento", "Responsavel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("equipamento", "Quantidade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("equipamento", "Estoque Minimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("equipamento", "Busca", None, QtGui.QApplication.UnicodeUTF8))
        self.btBusca.setText(QtGui.QApplication.translate("equipamento", "Pesquisar", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
