# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroequipamento.ui'
#
# Created: Fri Jan  7 15:51:11 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_equipamento(object):
    def setupUi(self, equipamento):
        equipamento.setObjectName("equipamento")
        equipamento.resize(668, 504)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/HP-Mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        equipamento.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(equipamento)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtGui.QFrame(equipamento)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btSalvar = QtGui.QPushButton(self.frame_3)
        self.btSalvar.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSalvar.setIcon(icon1)
        self.btSalvar.setFlat(True)
        self.btSalvar.setObjectName("btSalvar")
        self.horizontalLayout_2.addWidget(self.btSalvar)
        self.btCancelar = QtGui.QPushButton(self.frame_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/button_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCancelar.setIcon(icon2)
        self.btCancelar.setFlat(True)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_2.addWidget(self.btCancelar)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(equipamento)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.EditUnidade = QtGui.QLineEdit(self.frame_2)
        self.EditUnidade.setEnabled(True)
        self.EditUnidade.setObjectName("EditUnidade")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.EditUnidade)
        self.EditMarca = QtGui.QLineEdit(self.frame_2)
        self.EditMarca.setEnabled(True)
        self.EditMarca.setObjectName("EditMarca")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditMarca)
        self.EditNome = QtGui.QLineEdit(self.frame_2)
        self.EditNome.setEnabled(True)
        self.EditNome.setObjectName("EditNome")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditNome)
        self.EditID = QtGui.QLineEdit(self.frame_2)
        self.EditID.setEnabled(False)
        self.EditID.setObjectName("EditID")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.EditID)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.spinQtd = QtGui.QSpinBox(self.frame_2)
        self.spinQtd.setEnabled(True)
        self.spinQtd.setObjectName("spinQtd")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinQtd)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinEstMin = QtGui.QSpinBox(self.frame_2)
        self.spinEstMin.setEnabled(True)
        self.spinEstMin.setObjectName("spinEstMin")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinEstMin)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.comboReponsavel = QtGui.QComboBox(self.frame_2)
        self.comboReponsavel.setEnabled(True)
        self.comboReponsavel.setObjectName("comboReponsavel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboReponsavel)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(equipamento)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.PesquisaNome = QtGui.QLineEdit(self.frame)
        self.PesquisaNome.setObjectName("PesquisaNome")
        self.horizontalLayout_4.addWidget(self.PesquisaNome)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.PesquisaMarca = QtGui.QLineEdit(self.frame)
        self.PesquisaMarca.setText("")
        self.PesquisaMarca.setObjectName("PesquisaMarca")
        self.horizontalLayout_4.addWidget(self.PesquisaMarca)
        self.verticalLayout.addWidget(self.frame)
        self.frame_4 = QtGui.QFrame(equipamento)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabela = QtGui.QTableView(self.frame_4)
        self.tabela.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela.setTabKeyNavigation(False)
        self.tabela.setAlternatingRowColors(True)
        self.tabela.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabela.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabela.setSortingEnabled(True)
        self.tabela.setObjectName("tabela")
        self.tabela.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tabela)
        self.verticalLayout.addWidget(self.frame_4)
        self.label_3.setBuddy(self.EditUnidade)
        self.label_2.setBuddy(self.EditMarca)
        self.label.setBuddy(self.EditNome)

        self.retranslateUi(equipamento)
        QtCore.QMetaObject.connectSlotsByName(equipamento)
        equipamento.setTabOrder(self.EditNome, self.EditMarca)
        equipamento.setTabOrder(self.EditMarca, self.EditUnidade)
        equipamento.setTabOrder(self.EditUnidade, self.spinQtd)
        equipamento.setTabOrder(self.spinQtd, self.spinEstMin)
        equipamento.setTabOrder(self.spinEstMin, self.comboReponsavel)
        equipamento.setTabOrder(self.comboReponsavel, self.btSalvar)
        equipamento.setTabOrder(self.btSalvar, self.PesquisaNome)
        equipamento.setTabOrder(self.PesquisaNome, self.PesquisaMarca)
        equipamento.setTabOrder(self.PesquisaMarca, self.tabela)
        equipamento.setTabOrder(self.tabela, self.btCancelar)
        equipamento.setTabOrder(self.btCancelar, self.EditID)

    def retranslateUi(self, equipamento):
        equipamento.setWindowTitle(QtGui.QApplication.translate("equipamento", "Cadastro de Equipamento", None, QtGui.QApplication.UnicodeUTF8))
        self.btSalvar.setText(QtGui.QApplication.translate("equipamento", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.btCancelar.setText(QtGui.QApplication.translate("equipamento", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("equipamento", "Unidade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("equipamento", "Marca/Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("equipamento", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("equipamento", "Quantidade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("equipamento", "Estoque Minimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("equipamento", "Responsável", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("equipamento", "Buscar nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("equipamento", "Buscar marca", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
