# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrousuario.ui'
#
# Created: Tue Oct  5 20:36:22 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(814, 608)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/images/Profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 80, 801, 161))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayoutWidget = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 411, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.EditFuncao = QtGui.QLineEdit(self.formLayoutWidget)
        self.EditFuncao.setEnabled(False)
        self.EditFuncao.setObjectName("EditFuncao")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.EditFuncao)
        self.EditEmail = QtGui.QLineEdit(self.formLayoutWidget)
        self.EditEmail.setEnabled(False)
        self.EditEmail.setObjectName("EditEmail")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditEmail)
        self.EditNome = QtGui.QLineEdit(self.formLayoutWidget)
        self.EditNome.setEnabled(False)
        self.EditNome.setObjectName("EditNome")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditNome)
        self.EditID = QtGui.QLineEdit(self.formLayoutWidget)
        self.EditID.setEnabled(False)
        self.EditID.setObjectName("EditID")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.EditID)
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(420, 10, 381, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.EditConfirme = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.EditConfirme.setEnabled(False)
        self.EditConfirme.setEchoMode(QtGui.QLineEdit.Password)
        self.EditConfirme.setObjectName("EditConfirme")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.EditConfirme)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.EditSenha = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.EditSenha.setEnabled(False)
        self.EditSenha.setEchoMode(QtGui.QLineEdit.Password)
        self.EditSenha.setObjectName("EditSenha")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.EditSenha)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.EditLogin = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.EditLogin.setEnabled(False)
        self.EditLogin.setObjectName("EditLogin")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.EditLogin)
        self.ComboStatus = QtGui.QComboBox(self.formLayoutWidget_2)
        self.ComboStatus.setEnabled(False)
        self.ComboStatus.setObjectName("ComboStatus")
        self.ComboStatus.addItem("")
        self.ComboStatus.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.ComboStatus)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 801, 51))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Novo = QtGui.QPushButton(self.frame_3)
        self.Novo.setGeometry(QtCore.QRect(20, 10, 93, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/images/add_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Novo.setIcon(icon1)
        self.Novo.setObjectName("Novo")
        self.Salvar = QtGui.QPushButton(self.frame_3)
        self.Salvar.setEnabled(False)
        self.Salvar.setGeometry(QtCore.QRect(340, 10, 93, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/images/button_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Salvar.setIcon(icon2)
        self.Salvar.setObjectName("Salvar")
        self.Deletar = QtGui.QPushButton(self.frame_3)
        self.Deletar.setGeometry(QtCore.QRect(680, 10, 93, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/prefix1/images/remove_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Deletar.setIcon(icon3)
        self.Deletar.setObjectName("Deletar")
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(10, 280, 801, 281))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tabela = QtGui.QTableView(self.frame_4)
        self.tabela.setGeometry(QtCore.QRect(10, 10, 781, 291))
        self.tabela.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela.setTabKeyNavigation(False)
        self.tabela.setAlternatingRowColors(True)
        self.tabela.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabela.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabela.setSortingEnabled(True)
        self.tabela.setObjectName("tabela")
        self.tabela.horizontalHeader().setStretchLastSection(True)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 171, 20))
        self.label_7.setObjectName("label_7")
        self.Fechar = QtGui.QPushButton(Dialog)
        self.Fechar.setGeometry(QtCore.QRect(360, 570, 93, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/prefix1/images/button_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Fechar.setIcon(icon4)
        self.Fechar.setObjectName("Fechar")
        self.label_3.setBuddy(self.EditFuncao)
        self.label_2.setBuddy(self.EditEmail)
        self.label.setBuddy(self.EditNome)
        self.label_6.setBuddy(self.EditConfirme)
        self.label_5.setBuddy(self.EditSenha)
        self.label_4.setBuddy(self.EditLogin)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EditNome, self.EditEmail)
        Dialog.setTabOrder(self.EditEmail, self.EditFuncao)
        Dialog.setTabOrder(self.EditFuncao, self.ComboStatus)
        Dialog.setTabOrder(self.ComboStatus, self.EditLogin)
        Dialog.setTabOrder(self.EditLogin, self.EditSenha)
        Dialog.setTabOrder(self.EditSenha, self.EditConfirme)
        Dialog.setTabOrder(self.EditConfirme, self.Salvar)
        Dialog.setTabOrder(self.Salvar, self.Novo)
        Dialog.setTabOrder(self.Novo, self.EditID)
        Dialog.setTabOrder(self.EditID, self.Fechar)
        Dialog.setTabOrder(self.Fechar, self.Deletar)
        Dialog.setTabOrder(self.Deletar, self.tabela)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Cadastro de Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Função", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Confirmação", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Senha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboStatus.setItemText(0, QtGui.QApplication.translate("Dialog", "Ativo", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboStatus.setItemText(1, QtGui.QApplication.translate("Dialog", "Inativo", None, QtGui.QApplication.UnicodeUTF8))
        self.Novo.setText(QtGui.QApplication.translate("Dialog", "Novo", None, QtGui.QApplication.UnicodeUTF8))
        self.Salvar.setText(QtGui.QApplication.translate("Dialog", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.Deletar.setText(QtGui.QApplication.translate("Dialog", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "  Usuarios cadastrados", None, QtGui.QApplication.UnicodeUTF8))
        self.Fechar.setText(QtGui.QApplication.translate("Dialog", "Fechar", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
