# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Sat Oct  9 12:18:01 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_principal(object):
    def setupUi(self, principal):
        principal.setObjectName("principal")
        principal.resize(1000, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(principal.sizePolicy().hasHeightForWidth())
        principal.setSizePolicy(sizePolicy)
        principal.setMinimumSize(QtCore.QSize(1000, 720))
        self.centralwidget = QtGui.QWidget(principal)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 489))
        self.centralwidget.setObjectName("centralwidget")
        principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuCadastros = QtGui.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuPedidos = QtGui.QMenu(self.menubar)
        self.menuPedidos.setObjectName("menuPedidos")
        principal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(principal)
        self.statusbar.setObjectName("statusbar")
        principal.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(principal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        principal.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionAdcionar_usuario = QtGui.QAction(principal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/User-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdcionar_usuario.setIcon(icon)
        self.actionAdcionar_usuario.setObjectName("actionAdcionar_usuario")
        self.actionAdcionar_tecnico = QtGui.QAction(principal)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/technical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdcionar_tecnico.setIcon(icon1)
        self.actionAdcionar_tecnico.setObjectName("actionAdcionar_tecnico")
        self.actionAdcionar_equipamento = QtGui.QAction(principal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/HP-Mouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdcionar_equipamento.setIcon(icon2)
        self.actionAdcionar_equipamento.setObjectName("actionAdcionar_equipamento")
        self.actionAdcionar_departamento = QtGui.QAction(principal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/departamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdcionar_departamento.setIcon(icon3)
        self.actionAdcionar_departamento.setObjectName("actionAdcionar_departamento")
        self.actionAdcionar_subdepartamento = QtGui.QAction(principal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/subdepartamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdcionar_subdepartamento.setIcon(icon4)
        self.actionAdcionar_subdepartamento.setObjectName("actionAdcionar_subdepartamento")
        self.actionFazer_pedido_de_compra = QtGui.QAction(principal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/pedidodecompra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFazer_pedido_de_compra.setIcon(icon5)
        self.actionFazer_pedido_de_compra.setObjectName("actionFazer_pedido_de_compra")
        self.actionRealizar_baixa_no_estoque = QtGui.QAction(principal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/baixaestoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealizar_baixa_no_estoque.setIcon(icon6)
        self.actionRealizar_baixa_no_estoque.setObjectName("actionRealizar_baixa_no_estoque")
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuPedidos.menuAction())
        self.toolBar.addAction(self.actionFazer_pedido_de_compra)
        self.toolBar.addAction(self.actionRealizar_baixa_no_estoque)
        self.toolBar.addAction(self.actionAdcionar_usuario)
        self.toolBar.addAction(self.actionAdcionar_tecnico)
        self.toolBar.addAction(self.actionAdcionar_equipamento)
        self.toolBar.addAction(self.actionAdcionar_departamento)
        self.toolBar.addAction(self.actionAdcionar_subdepartamento)

        self.retranslateUi(principal)
        QtCore.QMetaObject.connectSlotsByName(principal)

    def retranslateUi(self, principal):
        principal.setWindowTitle(QtGui.QApplication.translate("principal", "Principal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArquivo.setTitle(QtGui.QApplication.translate("principal", "Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCadastros.setTitle(QtGui.QApplication.translate("principal", "Cadastros", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPedidos.setTitle(QtGui.QApplication.translate("principal", "Pedidos", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("principal", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdcionar_usuario.setText(QtGui.QApplication.translate("principal", "adicionar usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdcionar_tecnico.setText(QtGui.QApplication.translate("principal", "adicionar tecnico", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdcionar_equipamento.setText(QtGui.QApplication.translate("principal", "adicionar equipamento", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdcionar_departamento.setText(QtGui.QApplication.translate("principal", "adicionar departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdcionar_subdepartamento.setText(QtGui.QApplication.translate("principal", "adicionar subdepartamento", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFazer_pedido_de_compra.setText(QtGui.QApplication.translate("principal", "fazer pedido de compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRealizar_baixa_no_estoque.setText(QtGui.QApplication.translate("principal", "realizar baixa no estoque", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
